export const tournamentData = {
  "tournament": {
    "name_ar": "كأس الخليج العربي - خليجي 27",
    "name_en": "Arabian Gulf Cup 27",
    "edition": 27,
    "year": 2026,
    "host_country": "السعودية",
    "host_city": "جدة",
    "timezone": "Asia/Riyadh",
    "timezone_utc_offset": "+03:00",
    "teams": [
      "السعودية",
      "العراق",
      "عُمان",
      "الكويت",
      "الإمارات",
      "قطر",
      "البحرين",
      "اليمن"
    ],
    "groups": {
      "A": [
        "السعودية",
        "العراق",
        "عُمان",
        "الكويت"
      ],
      "B": [
        "الإمارات",
        "قطر",
        "البحرين",
        "اليمن"
      ]
    },
    "venues": [
      {
        "name_ar": "ملعب الإنماء بمدينة الملك عبدالله الرياضية",
        "city": "جدة",
        "country": "السعودية"
      },
      {
        "name_ar": "استاد الأمير عبدالله الفيصل الرياضي",
        "city": "جدة",
        "country": "السعودية"
      }
    ]
  },
  "matches": [
    {
      "match_number": 1,
      "stage": "group",
      "group": "A",
      "date": "2026-09-23",
      "time": "17:30",
      "timezone": "Asia/Riyadh",
      "home_team": "العراق",
      "away_team": "عُمان",
      "venue": "استاد الأمير عبدالله الفيصل الرياضي",
      "city": "جدة",
      "status": "finished",
      "home_score": 1,
      "away_score": 1
    },
    {
      "match_number": 2,
      "stage": "group",
      "group": "A",
      "date": "2026-09-23",
      "time": "21:00",
      "timezone": "Asia/Riyadh",
      "home_team": "السعودية",
      "away_team": "الكويت",
      "venue": "ملعب الإنماء بمدينة الملك عبدالله الرياضية",
      "city": "جدة",
      "status": "finished",
      "home_score": 1,
      "away_score": 0
    },
    {
      "match_number": 3,
      "stage": "group",
      "group": "B",
      "date": "2026-09-24",
      "time": "18:55",
      "timezone": "Asia/Riyadh",
      "home_team": "الإمارات",
      "away_team": "اليمن",
      "venue": "ملعب الإنماء بمدينة الملك عبدالله الرياضية",
      "city": "جدة",
      "status": "scheduled",
      "home_score": null,
      "away_score": null
    },
    {
      "match_number": 4,
      "stage": "group",
      "group": "B",
      "date": "2026-09-24",
      "time": "21:00",
      "timezone": "Asia/Riyadh",
      "home_team": "قطر",
      "away_team": "البحرين",
      "venue": "استاد الأمير عبدالله الفيصل الرياضي",
      "city": "جدة",
      "status": "scheduled",
      "home_score": null,
      "away_score": null
    },
    {
      "match_number": 5,
      "stage": "group",
      "group": "A",
      "date": "2026-09-26",
      "time": "18:55",
      "timezone": "Asia/Riyadh",
      "home_team": "الكويت",
      "away_team": "العراق",
      "venue": "استاد الأمير عبدالله الفيصل الرياضي",
      "city": "جدة",
      "status": "scheduled",
      "home_score": null,
      "away_score": null
    },
    {
      "match_number": 6,
      "stage": "group",
      "group": "A",
      "date": "2026-09-26",
      "time": "21:00",
      "timezone": "Asia/Riyadh",
      "home_team": "عُمان",
      "away_team": "السعودية",
      "venue": "ملعب الإنماء بمدينة الملك عبدالله الرياضية",
      "city": "جدة",
      "status": "scheduled",
      "home_score": null,
      "away_score": null
    },
    {
      "match_number": 7,
      "stage": "group",
      "group": "B",
      "date": "2026-09-27",
      "time": "18:55",
      "timezone": "Asia/Riyadh",
      "home_team": "اليمن",
      "away_team": "قطر",
      "venue": "ملعب الإنماء بمدينة الملك عبدالله الرياضية",
      "city": "جدة",
      "status": "scheduled",
      "home_score": null,
      "away_score": null
    },
    {
      "match_number": 8,
      "stage": "group",
      "group": "B",
      "date": "2026-09-27",
      "time": "21:00",
      "timezone": "Asia/Riyadh",
      "home_team": "البحرين",
      "away_team": "الإمارات",
      "venue": "استاد الأمير عبدالله الفيصل الرياضي",
      "city": "جدة",
      "status": "scheduled",
      "home_score": null,
      "away_score": null
    },
    {
      "match_number": 9,
      "stage": "group",
      "group": "A",
      "date": "2026-09-29",
      "time": "20:30",
      "timezone": "Asia/Riyadh",
      "home_team": "السعودية",
      "away_team": "العراق",
      "venue": "ملعب الإنماء بمدينة الملك عبدالله الرياضية",
      "city": "جدة",
      "status": "scheduled",
      "home_score": null,
      "away_score": null
    },
    {
      "match_number": 10,
      "stage": "group",
      "group": "A",
      "date": "2026-09-29",
      "time": "20:30",
      "timezone": "Asia/Riyadh",
      "home_team": "عُمان",
      "away_team": "الكويت",
      "venue": "استاد الأمير عبدالله الفيصل الرياضي",
      "city": "جدة",
      "status": "scheduled",
      "home_score": null,
      "away_score": null
    },
    {
      "match_number": 11,
      "stage": "group",
      "group": "B",
      "date": "2026-09-30",
      "time": "20:30",
      "timezone": "Asia/Riyadh",
      "home_team": "الإمارات",
      "away_team": "قطر",
      "venue": "ملعب الإنماء بمدينة الملك عبدالله الرياضية",
      "city": "جدة",
      "status": "scheduled",
      "home_score": null,
      "away_score": null
    },
    {
      "match_number": 12,
      "stage": "group",
      "group": "B",
      "date": "2026-09-30",
      "time": "20:30",
      "timezone": "Asia/Riyadh",
      "home_team": "البحرين",
      "away_team": "اليمن",
      "venue": "استاد الأمير عبدالله الفيصل الرياضي",
      "city": "جدة",
      "status": "scheduled",
      "home_score": null,
      "away_score": null
    },
    {
      "match_number": 13,
      "stage": "semifinal",
      "group": null,
      "date": "2026-10-03",
      "time": null,
      "timezone": "Asia/Riyadh",
      "home_team": "متصدر المجموعة A",
      "away_team": "وصيف المجموعة B",
      "venue": null,
      "city": "جدة",
      "status": "scheduled",
      "home_score": null,
      "away_score": null,
      "note": "وقت وملعب المباراة لم يكونا مثبتين بشكل رسمي في المصادر التي تم التحقق منها حتى 23 سبتمبر 2026."
    },
    {
      "match_number": 14,
      "stage": "semifinal",
      "group": null,
      "date": "2026-10-03",
      "time": null,
      "timezone": "Asia/Riyadh",
      "home_team": "متصدر المجموعة B",
      "away_team": "وصيف المجموعة A",
      "venue": null,
      "city": "جدة",
      "status": "scheduled",
      "home_score": null,
      "away_score": null,
      "note": "وقت وملعب المباراة لم يكونا مثبتين بشكل رسمي في المصادر التي تم التحقق منها حتى 23 سبتمبر 2026."
    },
    {
      "match_number": 15,
      "stage": "final",
      "group": null,
      "date": "2026-10-06",
      "time": null,
      "timezone": "Asia/Riyadh",
      "home_team": "الفائز من نصف النهائي 1",
      "away_team": "الفائز من نصف النهائي 2",
      "venue": "ملعب الإنماء بمدينة الملك عبدالله الرياضية",
      "city": "جدة",
      "status": "scheduled",
      "home_score": null,
      "away_score": null,
      "note": "وقت البداية لم يكن معلنًا رسميًا في المصادر التي تم التحقق منها حتى 23 سبتمبر 2026."
    }
  ],
  "data_quality": {
    "verified_as_of": "2026-09-23",
    "policy": "لا توجد بيانات مولدة أو مفترضة. الحقول غير المؤكدة رسميًا تُترك null بدل اختلاق قيمة.",
    "primary_source": "الاتحاد السعودي لكرة القدم",
    "secondary_sources": [
      "YallaKora",
      "365Scores",
      "Wego"
    ],
    "important": "نتائج المباراتين الأوليين محدثة وفق ما ظهر في المصادر وقت إنشاء الملف."
  }
} as const;
