import { ArrowUp, ChevronLeft, Facebook, Globe, Instagram, Menu, Moon, ShoppingCart, Ticket, Trophy, X, Youtube } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";

type GlobalHeaderProps = { onLogout?: () => void };

export function GlobalHeader({ onLogout }: GlobalHeaderProps) {
  const [open, setOpen] = useState(false);
  const [location] = useLocation();
  const navItems = [{ href: "/", label: "الرئيسية" }, { href: "/", label: "المباريات والنتائج" }, { href: "/", label: "المجموعات" }, { href: "/", label: "الملاعب" }, { href: "/", label: "الأخبار" }];
  const active = location === "/";
  return <header className="gc-header" dir="rtl"><div className="gc-header-container"><Link href="/" className="gc-brand" onClick={() => setOpen(false)}><div className="gc-logo-icon"><Trophy /></div><div className="gc-title-wrapper"><span className="gc-title">كأس الخليج العربي 27</span><span className="gc-subtitle">2026 - المملكة العربية السعودية</span></div></Link><nav><ul className="gc-nav">{navItems.map((item, index) => <li key={`${item.label}-${index}`}><Link href={item.href} className={`gc-nav-link ${active && index === 0 ? "active" : ""}`}>{item.label}</Link></li>)}</ul></nav><div className="gc-actions"><button className="gc-action-btn" title="تبديل المظهر" aria-label="تبديل المظهر"><Moon size={15} /></button><button className="gc-action-btn gc-lang-btn" title="تغيير اللغة"><Globe size={15} /><span>AR</span></button><button className="gc-action-btn" aria-label="السلة"><ShoppingCart size={15} /></button>{onLogout ? <button className="gc-cta-btn" onClick={onLogout}><Ticket size={15} /><span>تسجيل الخروج</span></button> : <Link href="/" className="gc-cta-btn"><Ticket size={15} /><span>احجز تذكرتك</span></Link>}<button className="gc-action-btn gc-mobile-toggle" onClick={() => setOpen(value => !value)} aria-label="القائمة">{open ? <X size={18} /> : <Menu size={18} />}</button></div></div><div className={`gc-mobile-drawer ${open ? "open" : ""}`}><ul className="gc-mobile-nav">{navItems.map((item, index) => <li key={`${item.label}-mobile-${index}`}><Link href={item.href} className={`gc-mobile-nav-link ${active && index === 0 ? "active" : ""}`} onClick={() => setOpen(false)}>{item.label}</Link></li>)}</ul></div></header>;
}

export function GlobalFooter() {
  const [showTop, setShowTop] = useState(false);
  useEffect(() => { const onScroll = () => setShowTop(window.scrollY > 250); window.addEventListener("scroll", onScroll); return () => window.removeEventListener("scroll", onScroll); }, []);
  return <><footer className="gc-footer" dir="rtl"><div className="gc-footer-container"><div className="gc-footer-grid"><div className="gc-footer-brand-info"><Link href="/" className="gc-brand"><div className="gc-logo-icon"><Trophy /></div><div className="gc-title-wrapper"><span className="gc-title">كأس الخليج العربي 27</span><span className="gc-subtitle">خليجي 27 - السعودية</span></div></Link><p>البوابة الرسمية لحجز تذاكر ومتابعة أحداث بطولة كأس الخليج العربي 2026. انضم إلينا لمعايشة الشغف الكروي الخليجي.</p><div className="gc-social-links"><a href="#" className="gc-social-btn" aria-label="X">𝕏</a><a href="#" className="gc-social-btn" aria-label="Instagram"><Instagram size={16} /></a><a href="#" className="gc-social-btn" aria-label="Facebook"><Facebook size={16} /></a><a href="#" className="gc-social-btn" aria-label="YouTube"><Youtube size={16} /></a></div></div><FooterColumn title="روابط سريعة" links={["جدول المباريات", "شراء التذاكر", "ترتيب المجموعات", "المرافق والملاعب"]} /><FooterColumn title="الدعم والمساعدة" links={["الأسئلة الشائعة", "مراكز حجز التذاكر", "سياسة الاسترجاع", "تواصل معنا"]} /><FooterColumn title="المنتخبات المشاركة" links={["السعودية - العراق - عمان", "الكويت - الإمارات - قطر", "البحرين - اليمن"]} /></div><div className="gc-footer-bottom"><div>© 2026 جميع الحقوق محفوظة لبطولة كأس الخليج العربي 27.</div><ul className="gc-legal-links"><li><a href="#" className="gc-legal-link">الشروط والأحكام</a></li><li><a href="#" className="gc-legal-link">سياسة الخصوصية</a></li><li><a href="#" className="gc-legal-link">ملفات تعريف الارتباط</a></li></ul></div></div></footer><button className={`gc-back-top-btn ${showTop ? "visible" : ""}`} onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} aria-label="الرجوع للأعلى"><ArrowUp size={17} /></button></>;
}

function FooterColumn({ title, links }: { title: string; links: string[] }) { return <div><h4 className="gc-footer-col-title">{title}</h4><ul className="gc-footer-links">{links.map(link => <li key={link}><a href="#" className="gc-footer-link"><ChevronLeft size={11} /> {link}</a></li>)}</ul></div>; }
